export const dummySkillRecords: SkillRecord[] = [
    {
        id: "skill_001",
        title: "Custom Agent",
        slug: "custom-agent",
        description: "A general-purpose custom agent for handling workflow automation tasks.",
        category: "automation",
        tags: ["agent", "workflow", "automation"],
        installCommand: "npm install custom-agent",
        createdAt: "2026-04-19T10:00:00.000Z",
        authorClerkId: "user_001",
        authorEmail: "author1@example.com",
    },
    {
        id: "skill_002",
        title: "Code Reviewer",
        slug: "code-reviewer",
        description: "Helps review pull requests and suggests improvements for code quality.",
        category: "development",
        tags: ["code", "review", "quality"],
        installCommand: "npm install code-reviewer",
        createdAt: "2026-04-18T09:30:00.000Z",
        authorClerkId: "user_002",
        authorEmail: "author2@example.com",
    },
    {
        id: "skill_003",
        title: "Data Cleaner",
        slug: "data-cleaner",
        description: "Cleans and normalizes messy datasets for analysis and reporting.",
        category: "data",
        tags: ["data", "cleanup", "normalization"],
        installCommand: "npm install data-cleaner",
        createdAt: "2026-04-17T14:15:00.000Z",
        authorClerkId: null,
        authorEmail: "author3@example.com",
    },
    {
        id: "skill_004",
        title: "Test Generator",
        slug: "test-generator",
        description: "Generates unit tests and helps improve test coverage automatically.",
        category: "testing",
        tags: ["tests", "coverage", "automation"],
        installCommand: "npm install test-generator",
        createdAt: null,
        authorClerkId: "user_004",
        authorEmail: null,
    },
    {
        id: "skill_005",
        title: "Documentation Writer",
        slug: "documentation-writer",
        description: "Creates and improves project documentation from source code and comments.",
        category: "documentation",
        tags: ["docs", "writing", "markdown"],
        installCommand: "npm install documentation-writer",
        createdAt: "2026-04-16T08:45:00.000Z",
        authorClerkId: "user_005",
        authorEmail: "author5@example.com",
    },
];
